#!/bin/bash
cat<<EOF
# .travis.yml automatically generated by "$0"

# Container-based builds used if "sudo: false" --> fast boot (1-6s)
# https://docs.travis-ci.com/user/ci-environment/
sudo: false

language: python

env:
$( tox -l | grep '^py' | sort -n | sed -e 's/^.*$/  - TOXENV="\0"/' )

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  coveralls
EOF
